version = "0.0.1"
print("Installation started...")
fs.makeDir("clock")
print("0%")
fs.copy("/disk/install/startup.lua", "startup.lua")
print("20%")
fs.copy("/disk/install/time.lua", "/clock/time.lua")
print("40%")
fs.copy("/disk/install/alarm.lua", "/clock/alarm.lua")
print("60%")
fs.copy("/disk/install/ring.lua", "/clock/ring.lua")
print("80%")
fs.copy("/disk/install/clear.lua", "/clock/clear.lua")
print("100%")
print("Installation complete!")
print("Remove disk and reboot system!")
